name: Reveal OCI Key
on:
  workflow_dispatch:

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Key
        env:
          KEY: ${{ secrets.OCI_PUBLIC_SSH_KEY }}
        run: |
          echo "Encoded Key: "
          echo "$KEY" | base64
